package com.crm.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table code_library
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CodeLibrary extends CodeLibraryKey {
    /**
     * Database Column Remarks:
     *   代码项名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.itemname
     *
     * @mbg.generated
     */
    private String itemname;

    /**
     * Database Column Remarks:
     *   排序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.sortno
     *
     * @mbg.generated
     */
    private String sortno;

    /**
     * Database Column Remarks:
     *   是否使用 1 是 0否
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.isinuse
     *
     * @mbg.generated
     */
    private String isinuse;

    /**
     * Database Column Remarks:
     *   代码项描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.itemdescribe
     *
     * @mbg.generated
     */
    private String itemdescribe;

    /**
     * Database Column Remarks:
     *   代码项属性
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.itemattribute
     *
     * @mbg.generated
     */
    private String itemattribute;

    /**
     * Database Column Remarks:
     *   属性1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.ATTRIBUTE1
     *
     * @mbg.generated
     */
    private String attribute1;

    /**
     * Database Column Remarks:
     *   属性2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.ATTRIBUTE2
     *
     * @mbg.generated
     */
    private String attribute2;

    /**
     * Database Column Remarks:
     *   属性3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.ATTRIBUTE3
     *
     * @mbg.generated
     */
    private String attribute3;

    /**
     * Database Column Remarks:
     *   属性4
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.ATTRIBUTE4
     *
     * @mbg.generated
     */
    private String attribute4;

    /**
     * Database Column Remarks:
     *   属性5
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.ATTRIBUTE5
     *
     * @mbg.generated
     */
    private String attribute5;

    /**
     * Database Column Remarks:
     *   属性6
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.ATTRIBUTE6
     *
     * @mbg.generated
     */
    private String attribute6;

    /**
     * Database Column Remarks:
     *   属性7
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.ATTRIBUTE7
     *
     * @mbg.generated
     */
    private String attribute7;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.itemname
     *
     * @return the value of code_library.itemname
     *
     * @mbg.generated
     */
    public String getItemname() {
        return itemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.itemname
     *
     * @param itemname the value for code_library.itemname
     *
     * @mbg.generated
     */
    public void setItemname(String itemname) {
        this.itemname = itemname == null ? null : itemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.sortno
     *
     * @return the value of code_library.sortno
     *
     * @mbg.generated
     */
    public String getSortno() {
        return sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.sortno
     *
     * @param sortno the value for code_library.sortno
     *
     * @mbg.generated
     */
    public void setSortno(String sortno) {
        this.sortno = sortno == null ? null : sortno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.isinuse
     *
     * @return the value of code_library.isinuse
     *
     * @mbg.generated
     */
    public String getIsinuse() {
        return isinuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.isinuse
     *
     * @param isinuse the value for code_library.isinuse
     *
     * @mbg.generated
     */
    public void setIsinuse(String isinuse) {
        this.isinuse = isinuse == null ? null : isinuse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.itemdescribe
     *
     * @return the value of code_library.itemdescribe
     *
     * @mbg.generated
     */
    public String getItemdescribe() {
        return itemdescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.itemdescribe
     *
     * @param itemdescribe the value for code_library.itemdescribe
     *
     * @mbg.generated
     */
    public void setItemdescribe(String itemdescribe) {
        this.itemdescribe = itemdescribe == null ? null : itemdescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.itemattribute
     *
     * @return the value of code_library.itemattribute
     *
     * @mbg.generated
     */
    public String getItemattribute() {
        return itemattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.itemattribute
     *
     * @param itemattribute the value for code_library.itemattribute
     *
     * @mbg.generated
     */
    public void setItemattribute(String itemattribute) {
        this.itemattribute = itemattribute == null ? null : itemattribute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.ATTRIBUTE1
     *
     * @return the value of code_library.ATTRIBUTE1
     *
     * @mbg.generated
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.ATTRIBUTE1
     *
     * @param attribute1 the value for code_library.ATTRIBUTE1
     *
     * @mbg.generated
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1 == null ? null : attribute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.ATTRIBUTE2
     *
     * @return the value of code_library.ATTRIBUTE2
     *
     * @mbg.generated
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.ATTRIBUTE2
     *
     * @param attribute2 the value for code_library.ATTRIBUTE2
     *
     * @mbg.generated
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2 == null ? null : attribute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.ATTRIBUTE3
     *
     * @return the value of code_library.ATTRIBUTE3
     *
     * @mbg.generated
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.ATTRIBUTE3
     *
     * @param attribute3 the value for code_library.ATTRIBUTE3
     *
     * @mbg.generated
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3 == null ? null : attribute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.ATTRIBUTE4
     *
     * @return the value of code_library.ATTRIBUTE4
     *
     * @mbg.generated
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.ATTRIBUTE4
     *
     * @param attribute4 the value for code_library.ATTRIBUTE4
     *
     * @mbg.generated
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4 == null ? null : attribute4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.ATTRIBUTE5
     *
     * @return the value of code_library.ATTRIBUTE5
     *
     * @mbg.generated
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.ATTRIBUTE5
     *
     * @param attribute5 the value for code_library.ATTRIBUTE5
     *
     * @mbg.generated
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5 == null ? null : attribute5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.ATTRIBUTE6
     *
     * @return the value of code_library.ATTRIBUTE6
     *
     * @mbg.generated
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.ATTRIBUTE6
     *
     * @param attribute6 the value for code_library.ATTRIBUTE6
     *
     * @mbg.generated
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6 == null ? null : attribute6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.ATTRIBUTE7
     *
     * @return the value of code_library.ATTRIBUTE7
     *
     * @mbg.generated
     */
    public String getAttribute7() {
        return attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.ATTRIBUTE7
     *
     * @param attribute7 the value for code_library.ATTRIBUTE7
     *
     * @mbg.generated
     */
    public void setAttribute7(String attribute7) {
        this.attribute7 = attribute7 == null ? null : attribute7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.remark
     *
     * @return the value of code_library.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.remark
     *
     * @param remark the value for code_library.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.update_time
     *
     * @return the value of code_library.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.update_time
     *
     * @param updateTime the value for code_library.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}