package com.crm.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    public OrderDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSerialnoIsNull() {
            addCriterion("serialno is null");
            return (Criteria) this;
        }

        public Criteria andSerialnoIsNotNull() {
            addCriterion("serialno is not null");
            return (Criteria) this;
        }

        public Criteria andSerialnoEqualTo(String value) {
            addCriterion("serialno =", value, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoNotEqualTo(String value) {
            addCriterion("serialno <>", value, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoGreaterThan(String value) {
            addCriterion("serialno >", value, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoGreaterThanOrEqualTo(String value) {
            addCriterion("serialno >=", value, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoLessThan(String value) {
            addCriterion("serialno <", value, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoLessThanOrEqualTo(String value) {
            addCriterion("serialno <=", value, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoLike(String value) {
            addCriterion("serialno like", value, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoNotLike(String value) {
            addCriterion("serialno not like", value, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoIn(List<String> values) {
            addCriterion("serialno in", values, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoNotIn(List<String> values) {
            addCriterion("serialno not in", values, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoBetween(String value1, String value2) {
            addCriterion("serialno between", value1, value2, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoNotBetween(String value1, String value2) {
            addCriterion("serialno not between", value1, value2, "serialno");
            return (Criteria) this;
        }

        public Criteria andOrdernoIsNull() {
            addCriterion("orderno is null");
            return (Criteria) this;
        }

        public Criteria andOrdernoIsNotNull() {
            addCriterion("orderno is not null");
            return (Criteria) this;
        }

        public Criteria andOrdernoEqualTo(String value) {
            addCriterion("orderno =", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotEqualTo(String value) {
            addCriterion("orderno <>", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoGreaterThan(String value) {
            addCriterion("orderno >", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoGreaterThanOrEqualTo(String value) {
            addCriterion("orderno >=", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLessThan(String value) {
            addCriterion("orderno <", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLessThanOrEqualTo(String value) {
            addCriterion("orderno <=", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLike(String value) {
            addCriterion("orderno like", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotLike(String value) {
            addCriterion("orderno not like", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoIn(List<String> values) {
            addCriterion("orderno in", values, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotIn(List<String> values) {
            addCriterion("orderno not in", values, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoBetween(String value1, String value2) {
            addCriterion("orderno between", value1, value2, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotBetween(String value1, String value2) {
            addCriterion("orderno not between", value1, value2, "orderno");
            return (Criteria) this;
        }

        public Criteria andGoodsidIsNull() {
            addCriterion("goodsID is null");
            return (Criteria) this;
        }

        public Criteria andGoodsidIsNotNull() {
            addCriterion("goodsID is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsidEqualTo(String value) {
            addCriterion("goodsID =", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotEqualTo(String value) {
            addCriterion("goodsID <>", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidGreaterThan(String value) {
            addCriterion("goodsID >", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidGreaterThanOrEqualTo(String value) {
            addCriterion("goodsID >=", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidLessThan(String value) {
            addCriterion("goodsID <", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidLessThanOrEqualTo(String value) {
            addCriterion("goodsID <=", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidLike(String value) {
            addCriterion("goodsID like", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotLike(String value) {
            addCriterion("goodsID not like", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidIn(List<String> values) {
            addCriterion("goodsID in", values, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotIn(List<String> values) {
            addCriterion("goodsID not in", values, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidBetween(String value1, String value2) {
            addCriterion("goodsID between", value1, value2, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotBetween(String value1, String value2) {
            addCriterion("goodsID not between", value1, value2, "goodsid");
            return (Criteria) this;
        }

        public Criteria andBatchnoIsNull() {
            addCriterion("batchno is null");
            return (Criteria) this;
        }

        public Criteria andBatchnoIsNotNull() {
            addCriterion("batchno is not null");
            return (Criteria) this;
        }

        public Criteria andBatchnoEqualTo(String value) {
            addCriterion("batchno =", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoNotEqualTo(String value) {
            addCriterion("batchno <>", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoGreaterThan(String value) {
            addCriterion("batchno >", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoGreaterThanOrEqualTo(String value) {
            addCriterion("batchno >=", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoLessThan(String value) {
            addCriterion("batchno <", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoLessThanOrEqualTo(String value) {
            addCriterion("batchno <=", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoLike(String value) {
            addCriterion("batchno like", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoNotLike(String value) {
            addCriterion("batchno not like", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoIn(List<String> values) {
            addCriterion("batchno in", values, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoNotIn(List<String> values) {
            addCriterion("batchno not in", values, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoBetween(String value1, String value2) {
            addCriterion("batchno between", value1, value2, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoNotBetween(String value1, String value2) {
            addCriterion("batchno not between", value1, value2, "batchno");
            return (Criteria) this;
        }

        public Criteria andGoodsnameIsNull() {
            addCriterion("goodsname is null");
            return (Criteria) this;
        }

        public Criteria andGoodsnameIsNotNull() {
            addCriterion("goodsname is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsnameEqualTo(String value) {
            addCriterion("goodsname =", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameNotEqualTo(String value) {
            addCriterion("goodsname <>", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameGreaterThan(String value) {
            addCriterion("goodsname >", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameGreaterThanOrEqualTo(String value) {
            addCriterion("goodsname >=", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameLessThan(String value) {
            addCriterion("goodsname <", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameLessThanOrEqualTo(String value) {
            addCriterion("goodsname <=", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameLike(String value) {
            addCriterion("goodsname like", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameNotLike(String value) {
            addCriterion("goodsname not like", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameIn(List<String> values) {
            addCriterion("goodsname in", values, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameNotIn(List<String> values) {
            addCriterion("goodsname not in", values, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameBetween(String value1, String value2) {
            addCriterion("goodsname between", value1, value2, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameNotBetween(String value1, String value2) {
            addCriterion("goodsname not between", value1, value2, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsypeIsNull() {
            addCriterion("goodsype is null");
            return (Criteria) this;
        }

        public Criteria andGoodsypeIsNotNull() {
            addCriterion("goodsype is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsypeEqualTo(String value) {
            addCriterion("goodsype =", value, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeNotEqualTo(String value) {
            addCriterion("goodsype <>", value, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeGreaterThan(String value) {
            addCriterion("goodsype >", value, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeGreaterThanOrEqualTo(String value) {
            addCriterion("goodsype >=", value, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeLessThan(String value) {
            addCriterion("goodsype <", value, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeLessThanOrEqualTo(String value) {
            addCriterion("goodsype <=", value, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeLike(String value) {
            addCriterion("goodsype like", value, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeNotLike(String value) {
            addCriterion("goodsype not like", value, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeIn(List<String> values) {
            addCriterion("goodsype in", values, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeNotIn(List<String> values) {
            addCriterion("goodsype not in", values, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeBetween(String value1, String value2) {
            addCriterion("goodsype between", value1, value2, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeNotBetween(String value1, String value2) {
            addCriterion("goodsype not between", value1, value2, "goodsype");
            return (Criteria) this;
        }

        public Criteria andPurchasepriceIsNull() {
            addCriterion("purchasePrice is null");
            return (Criteria) this;
        }

        public Criteria andPurchasepriceIsNotNull() {
            addCriterion("purchasePrice is not null");
            return (Criteria) this;
        }

        public Criteria andPurchasepriceEqualTo(BigDecimal value) {
            addCriterion("purchasePrice =", value, "purchaseprice");
            return (Criteria) this;
        }

        public Criteria andPurchasepriceNotEqualTo(BigDecimal value) {
            addCriterion("purchasePrice <>", value, "purchaseprice");
            return (Criteria) this;
        }

        public Criteria andPurchasepriceGreaterThan(BigDecimal value) {
            addCriterion("purchasePrice >", value, "purchaseprice");
            return (Criteria) this;
        }

        public Criteria andPurchasepriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("purchasePrice >=", value, "purchaseprice");
            return (Criteria) this;
        }

        public Criteria andPurchasepriceLessThan(BigDecimal value) {
            addCriterion("purchasePrice <", value, "purchaseprice");
            return (Criteria) this;
        }

        public Criteria andPurchasepriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("purchasePrice <=", value, "purchaseprice");
            return (Criteria) this;
        }

        public Criteria andPurchasepriceIn(List<BigDecimal> values) {
            addCriterion("purchasePrice in", values, "purchaseprice");
            return (Criteria) this;
        }

        public Criteria andPurchasepriceNotIn(List<BigDecimal> values) {
            addCriterion("purchasePrice not in", values, "purchaseprice");
            return (Criteria) this;
        }

        public Criteria andPurchasepriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("purchasePrice between", value1, value2, "purchaseprice");
            return (Criteria) this;
        }

        public Criteria andPurchasepriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("purchasePrice not between", value1, value2, "purchaseprice");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andRepairdateIsNull() {
            addCriterion("repairdate is null");
            return (Criteria) this;
        }

        public Criteria andRepairdateIsNotNull() {
            addCriterion("repairdate is not null");
            return (Criteria) this;
        }

        public Criteria andRepairdateEqualTo(String value) {
            addCriterion("repairdate =", value, "repairdate");
            return (Criteria) this;
        }

        public Criteria andRepairdateNotEqualTo(String value) {
            addCriterion("repairdate <>", value, "repairdate");
            return (Criteria) this;
        }

        public Criteria andRepairdateGreaterThan(String value) {
            addCriterion("repairdate >", value, "repairdate");
            return (Criteria) this;
        }

        public Criteria andRepairdateGreaterThanOrEqualTo(String value) {
            addCriterion("repairdate >=", value, "repairdate");
            return (Criteria) this;
        }

        public Criteria andRepairdateLessThan(String value) {
            addCriterion("repairdate <", value, "repairdate");
            return (Criteria) this;
        }

        public Criteria andRepairdateLessThanOrEqualTo(String value) {
            addCriterion("repairdate <=", value, "repairdate");
            return (Criteria) this;
        }

        public Criteria andRepairdateLike(String value) {
            addCriterion("repairdate like", value, "repairdate");
            return (Criteria) this;
        }

        public Criteria andRepairdateNotLike(String value) {
            addCriterion("repairdate not like", value, "repairdate");
            return (Criteria) this;
        }

        public Criteria andRepairdateIn(List<String> values) {
            addCriterion("repairdate in", values, "repairdate");
            return (Criteria) this;
        }

        public Criteria andRepairdateNotIn(List<String> values) {
            addCriterion("repairdate not in", values, "repairdate");
            return (Criteria) this;
        }

        public Criteria andRepairdateBetween(String value1, String value2) {
            addCriterion("repairdate between", value1, value2, "repairdate");
            return (Criteria) this;
        }

        public Criteria andRepairdateNotBetween(String value1, String value2) {
            addCriterion("repairdate not between", value1, value2, "repairdate");
            return (Criteria) this;
        }

        public Criteria andTermmonthIsNull() {
            addCriterion("termmonth is null");
            return (Criteria) this;
        }

        public Criteria andTermmonthIsNotNull() {
            addCriterion("termmonth is not null");
            return (Criteria) this;
        }

        public Criteria andTermmonthEqualTo(String value) {
            addCriterion("termmonth =", value, "termmonth");
            return (Criteria) this;
        }

        public Criteria andTermmonthNotEqualTo(String value) {
            addCriterion("termmonth <>", value, "termmonth");
            return (Criteria) this;
        }

        public Criteria andTermmonthGreaterThan(String value) {
            addCriterion("termmonth >", value, "termmonth");
            return (Criteria) this;
        }

        public Criteria andTermmonthGreaterThanOrEqualTo(String value) {
            addCriterion("termmonth >=", value, "termmonth");
            return (Criteria) this;
        }

        public Criteria andTermmonthLessThan(String value) {
            addCriterion("termmonth <", value, "termmonth");
            return (Criteria) this;
        }

        public Criteria andTermmonthLessThanOrEqualTo(String value) {
            addCriterion("termmonth <=", value, "termmonth");
            return (Criteria) this;
        }

        public Criteria andTermmonthLike(String value) {
            addCriterion("termmonth like", value, "termmonth");
            return (Criteria) this;
        }

        public Criteria andTermmonthNotLike(String value) {
            addCriterion("termmonth not like", value, "termmonth");
            return (Criteria) this;
        }

        public Criteria andTermmonthIn(List<String> values) {
            addCriterion("termmonth in", values, "termmonth");
            return (Criteria) this;
        }

        public Criteria andTermmonthNotIn(List<String> values) {
            addCriterion("termmonth not in", values, "termmonth");
            return (Criteria) this;
        }

        public Criteria andTermmonthBetween(String value1, String value2) {
            addCriterion("termmonth between", value1, value2, "termmonth");
            return (Criteria) this;
        }

        public Criteria andTermmonthNotBetween(String value1, String value2) {
            addCriterion("termmonth not between", value1, value2, "termmonth");
            return (Criteria) this;
        }

        public Criteria andOverduedateIsNull() {
            addCriterion("overduedate is null");
            return (Criteria) this;
        }

        public Criteria andOverduedateIsNotNull() {
            addCriterion("overduedate is not null");
            return (Criteria) this;
        }

        public Criteria andOverduedateEqualTo(String value) {
            addCriterion("overduedate =", value, "overduedate");
            return (Criteria) this;
        }

        public Criteria andOverduedateNotEqualTo(String value) {
            addCriterion("overduedate <>", value, "overduedate");
            return (Criteria) this;
        }

        public Criteria andOverduedateGreaterThan(String value) {
            addCriterion("overduedate >", value, "overduedate");
            return (Criteria) this;
        }

        public Criteria andOverduedateGreaterThanOrEqualTo(String value) {
            addCriterion("overduedate >=", value, "overduedate");
            return (Criteria) this;
        }

        public Criteria andOverduedateLessThan(String value) {
            addCriterion("overduedate <", value, "overduedate");
            return (Criteria) this;
        }

        public Criteria andOverduedateLessThanOrEqualTo(String value) {
            addCriterion("overduedate <=", value, "overduedate");
            return (Criteria) this;
        }

        public Criteria andOverduedateLike(String value) {
            addCriterion("overduedate like", value, "overduedate");
            return (Criteria) this;
        }

        public Criteria andOverduedateNotLike(String value) {
            addCriterion("overduedate not like", value, "overduedate");
            return (Criteria) this;
        }

        public Criteria andOverduedateIn(List<String> values) {
            addCriterion("overduedate in", values, "overduedate");
            return (Criteria) this;
        }

        public Criteria andOverduedateNotIn(List<String> values) {
            addCriterion("overduedate not in", values, "overduedate");
            return (Criteria) this;
        }

        public Criteria andOverduedateBetween(String value1, String value2) {
            addCriterion("overduedate between", value1, value2, "overduedate");
            return (Criteria) this;
        }

        public Criteria andOverduedateNotBetween(String value1, String value2) {
            addCriterion("overduedate not between", value1, value2, "overduedate");
            return (Criteria) this;
        }

        public Criteria andNextrepairdateIsNull() {
            addCriterion("nextrepairdate is null");
            return (Criteria) this;
        }

        public Criteria andNextrepairdateIsNotNull() {
            addCriterion("nextrepairdate is not null");
            return (Criteria) this;
        }

        public Criteria andNextrepairdateEqualTo(String value) {
            addCriterion("nextrepairdate =", value, "nextrepairdate");
            return (Criteria) this;
        }

        public Criteria andNextrepairdateNotEqualTo(String value) {
            addCriterion("nextrepairdate <>", value, "nextrepairdate");
            return (Criteria) this;
        }

        public Criteria andNextrepairdateGreaterThan(String value) {
            addCriterion("nextrepairdate >", value, "nextrepairdate");
            return (Criteria) this;
        }

        public Criteria andNextrepairdateGreaterThanOrEqualTo(String value) {
            addCriterion("nextrepairdate >=", value, "nextrepairdate");
            return (Criteria) this;
        }

        public Criteria andNextrepairdateLessThan(String value) {
            addCriterion("nextrepairdate <", value, "nextrepairdate");
            return (Criteria) this;
        }

        public Criteria andNextrepairdateLessThanOrEqualTo(String value) {
            addCriterion("nextrepairdate <=", value, "nextrepairdate");
            return (Criteria) this;
        }

        public Criteria andNextrepairdateLike(String value) {
            addCriterion("nextrepairdate like", value, "nextrepairdate");
            return (Criteria) this;
        }

        public Criteria andNextrepairdateNotLike(String value) {
            addCriterion("nextrepairdate not like", value, "nextrepairdate");
            return (Criteria) this;
        }

        public Criteria andNextrepairdateIn(List<String> values) {
            addCriterion("nextrepairdate in", values, "nextrepairdate");
            return (Criteria) this;
        }

        public Criteria andNextrepairdateNotIn(List<String> values) {
            addCriterion("nextrepairdate not in", values, "nextrepairdate");
            return (Criteria) this;
        }

        public Criteria andNextrepairdateBetween(String value1, String value2) {
            addCriterion("nextrepairdate between", value1, value2, "nextrepairdate");
            return (Criteria) this;
        }

        public Criteria andNextrepairdateNotBetween(String value1, String value2) {
            addCriterion("nextrepairdate not between", value1, value2, "nextrepairdate");
            return (Criteria) this;
        }

        public Criteria andOpenuserIsNull() {
            addCriterion("openuser is null");
            return (Criteria) this;
        }

        public Criteria andOpenuserIsNotNull() {
            addCriterion("openuser is not null");
            return (Criteria) this;
        }

        public Criteria andOpenuserEqualTo(String value) {
            addCriterion("openuser =", value, "openuser");
            return (Criteria) this;
        }

        public Criteria andOpenuserNotEqualTo(String value) {
            addCriterion("openuser <>", value, "openuser");
            return (Criteria) this;
        }

        public Criteria andOpenuserGreaterThan(String value) {
            addCriterion("openuser >", value, "openuser");
            return (Criteria) this;
        }

        public Criteria andOpenuserGreaterThanOrEqualTo(String value) {
            addCriterion("openuser >=", value, "openuser");
            return (Criteria) this;
        }

        public Criteria andOpenuserLessThan(String value) {
            addCriterion("openuser <", value, "openuser");
            return (Criteria) this;
        }

        public Criteria andOpenuserLessThanOrEqualTo(String value) {
            addCriterion("openuser <=", value, "openuser");
            return (Criteria) this;
        }

        public Criteria andOpenuserLike(String value) {
            addCriterion("openuser like", value, "openuser");
            return (Criteria) this;
        }

        public Criteria andOpenuserNotLike(String value) {
            addCriterion("openuser not like", value, "openuser");
            return (Criteria) this;
        }

        public Criteria andOpenuserIn(List<String> values) {
            addCriterion("openuser in", values, "openuser");
            return (Criteria) this;
        }

        public Criteria andOpenuserNotIn(List<String> values) {
            addCriterion("openuser not in", values, "openuser");
            return (Criteria) this;
        }

        public Criteria andOpenuserBetween(String value1, String value2) {
            addCriterion("openuser between", value1, value2, "openuser");
            return (Criteria) this;
        }

        public Criteria andOpenuserNotBetween(String value1, String value2) {
            addCriterion("openuser not between", value1, value2, "openuser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_detail
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}