package com.crm.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class OrderInfo {
    /**
     * Database Column Remarks:
     *   订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.orderno
     *
     * @mbg.generated
     */
    private String orderno;

    /**
     * Database Column Remarks:
     *   车牌号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.carid
     *
     * @mbg.generated
     */
    private String carid;

    /**
     * Database Column Remarks:
     *   订单总金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   优惠金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.preferentialamount
     *
     * @mbg.generated
     */
    private BigDecimal preferentialamount;

    /**
     * Database Column Remarks:
     *   订单应付总金额（总金额-优惠金额）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.orderamount
     *
     * @mbg.generated
     */
    private BigDecimal orderamount;

    /**
     * Database Column Remarks:
     *   应付未付金额 （欠账金额）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.oweamount
     *
     * @mbg.generated
     */
    private BigDecimal oweamount;

    /**
     * Database Column Remarks:
     *   实付金额 （实付+欠账=应付总金额）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.actualpayamount
     *
     * @mbg.generated
     */
    private BigDecimal actualpayamount;

    /**
     * Database Column Remarks:
     *   订单状态 1完成 0赊账
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.orderstatus
     *
     * @mbg.generated
     */
    private String orderstatus;

    /**
     * Database Column Remarks:
     *   开单人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.openuser
     *
     * @mbg.generated
     */
    private String openuser;

    /**
     * Database Column Remarks:
     *   开单时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.orderno
     *
     * @return the value of order_info.orderno
     *
     * @mbg.generated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.orderno
     *
     * @param orderno the value for order_info.orderno
     *
     * @mbg.generated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.carid
     *
     * @return the value of order_info.carid
     *
     * @mbg.generated
     */
    public String getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.carid
     *
     * @param carid the value for order_info.carid
     *
     * @mbg.generated
     */
    public void setCarid(String carid) {
        this.carid = carid == null ? null : carid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.amount
     *
     * @return the value of order_info.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.amount
     *
     * @param amount the value for order_info.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.preferentialamount
     *
     * @return the value of order_info.preferentialamount
     *
     * @mbg.generated
     */
    public BigDecimal getPreferentialamount() {
        return preferentialamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.preferentialamount
     *
     * @param preferentialamount the value for order_info.preferentialamount
     *
     * @mbg.generated
     */
    public void setPreferentialamount(BigDecimal preferentialamount) {
        this.preferentialamount = preferentialamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.orderamount
     *
     * @return the value of order_info.orderamount
     *
     * @mbg.generated
     */
    public BigDecimal getOrderamount() {
        return orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.orderamount
     *
     * @param orderamount the value for order_info.orderamount
     *
     * @mbg.generated
     */
    public void setOrderamount(BigDecimal orderamount) {
        this.orderamount = orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.oweamount
     *
     * @return the value of order_info.oweamount
     *
     * @mbg.generated
     */
    public BigDecimal getOweamount() {
        return oweamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.oweamount
     *
     * @param oweamount the value for order_info.oweamount
     *
     * @mbg.generated
     */
    public void setOweamount(BigDecimal oweamount) {
        this.oweamount = oweamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.actualpayamount
     *
     * @return the value of order_info.actualpayamount
     *
     * @mbg.generated
     */
    public BigDecimal getActualpayamount() {
        return actualpayamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.actualpayamount
     *
     * @param actualpayamount the value for order_info.actualpayamount
     *
     * @mbg.generated
     */
    public void setActualpayamount(BigDecimal actualpayamount) {
        this.actualpayamount = actualpayamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.orderstatus
     *
     * @return the value of order_info.orderstatus
     *
     * @mbg.generated
     */
    public String getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.orderstatus
     *
     * @param orderstatus the value for order_info.orderstatus
     *
     * @mbg.generated
     */
    public void setOrderstatus(String orderstatus) {
        this.orderstatus = orderstatus == null ? null : orderstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.openuser
     *
     * @return the value of order_info.openuser
     *
     * @mbg.generated
     */
    public String getOpenuser() {
        return openuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.openuser
     *
     * @param openuser the value for order_info.openuser
     *
     * @mbg.generated
     */
    public void setOpenuser(String openuser) {
        this.openuser = openuser == null ? null : openuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.update_time
     *
     * @return the value of order_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.update_time
     *
     * @param updateTime the value for order_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.remark
     *
     * @return the value of order_info.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.remark
     *
     * @param remark the value for order_info.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}