package com.crm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StockInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_info
     *
     * @mbg.generated
     */
    public StockInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGoodsidIsNull() {
            addCriterion("goodsID is null");
            return (Criteria) this;
        }

        public Criteria andGoodsidIsNotNull() {
            addCriterion("goodsID is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsidEqualTo(String value) {
            addCriterion("goodsID =", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotEqualTo(String value) {
            addCriterion("goodsID <>", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidGreaterThan(String value) {
            addCriterion("goodsID >", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidGreaterThanOrEqualTo(String value) {
            addCriterion("goodsID >=", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidLessThan(String value) {
            addCriterion("goodsID <", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidLessThanOrEqualTo(String value) {
            addCriterion("goodsID <=", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidLike(String value) {
            addCriterion("goodsID like", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotLike(String value) {
            addCriterion("goodsID not like", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidIn(List<String> values) {
            addCriterion("goodsID in", values, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotIn(List<String> values) {
            addCriterion("goodsID not in", values, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidBetween(String value1, String value2) {
            addCriterion("goodsID between", value1, value2, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotBetween(String value1, String value2) {
            addCriterion("goodsID not between", value1, value2, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsnameIsNull() {
            addCriterion("goodsname is null");
            return (Criteria) this;
        }

        public Criteria andGoodsnameIsNotNull() {
            addCriterion("goodsname is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsnameEqualTo(String value) {
            addCriterion("goodsname =", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameNotEqualTo(String value) {
            addCriterion("goodsname <>", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameGreaterThan(String value) {
            addCriterion("goodsname >", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameGreaterThanOrEqualTo(String value) {
            addCriterion("goodsname >=", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameLessThan(String value) {
            addCriterion("goodsname <", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameLessThanOrEqualTo(String value) {
            addCriterion("goodsname <=", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameLike(String value) {
            addCriterion("goodsname like", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameNotLike(String value) {
            addCriterion("goodsname not like", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameIn(List<String> values) {
            addCriterion("goodsname in", values, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameNotIn(List<String> values) {
            addCriterion("goodsname not in", values, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameBetween(String value1, String value2) {
            addCriterion("goodsname between", value1, value2, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameNotBetween(String value1, String value2) {
            addCriterion("goodsname not between", value1, value2, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsypeIsNull() {
            addCriterion("goodsype is null");
            return (Criteria) this;
        }

        public Criteria andGoodsypeIsNotNull() {
            addCriterion("goodsype is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsypeEqualTo(String value) {
            addCriterion("goodsype =", value, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeNotEqualTo(String value) {
            addCriterion("goodsype <>", value, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeGreaterThan(String value) {
            addCriterion("goodsype >", value, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeGreaterThanOrEqualTo(String value) {
            addCriterion("goodsype >=", value, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeLessThan(String value) {
            addCriterion("goodsype <", value, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeLessThanOrEqualTo(String value) {
            addCriterion("goodsype <=", value, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeLike(String value) {
            addCriterion("goodsype like", value, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeNotLike(String value) {
            addCriterion("goodsype not like", value, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeIn(List<String> values) {
            addCriterion("goodsype in", values, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeNotIn(List<String> values) {
            addCriterion("goodsype not in", values, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeBetween(String value1, String value2) {
            addCriterion("goodsype between", value1, value2, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodsypeNotBetween(String value1, String value2) {
            addCriterion("goodsype not between", value1, value2, "goodsype");
            return (Criteria) this;
        }

        public Criteria andGoodscountIsNull() {
            addCriterion("goodscount is null");
            return (Criteria) this;
        }

        public Criteria andGoodscountIsNotNull() {
            addCriterion("goodscount is not null");
            return (Criteria) this;
        }

        public Criteria andGoodscountEqualTo(String value) {
            addCriterion("goodscount =", value, "goodscount");
            return (Criteria) this;
        }

        public Criteria andGoodscountNotEqualTo(String value) {
            addCriterion("goodscount <>", value, "goodscount");
            return (Criteria) this;
        }

        public Criteria andGoodscountGreaterThan(String value) {
            addCriterion("goodscount >", value, "goodscount");
            return (Criteria) this;
        }

        public Criteria andGoodscountGreaterThanOrEqualTo(String value) {
            addCriterion("goodscount >=", value, "goodscount");
            return (Criteria) this;
        }

        public Criteria andGoodscountLessThan(String value) {
            addCriterion("goodscount <", value, "goodscount");
            return (Criteria) this;
        }

        public Criteria andGoodscountLessThanOrEqualTo(String value) {
            addCriterion("goodscount <=", value, "goodscount");
            return (Criteria) this;
        }

        public Criteria andGoodscountLike(String value) {
            addCriterion("goodscount like", value, "goodscount");
            return (Criteria) this;
        }

        public Criteria andGoodscountNotLike(String value) {
            addCriterion("goodscount not like", value, "goodscount");
            return (Criteria) this;
        }

        public Criteria andGoodscountIn(List<String> values) {
            addCriterion("goodscount in", values, "goodscount");
            return (Criteria) this;
        }

        public Criteria andGoodscountNotIn(List<String> values) {
            addCriterion("goodscount not in", values, "goodscount");
            return (Criteria) this;
        }

        public Criteria andGoodscountBetween(String value1, String value2) {
            addCriterion("goodscount between", value1, value2, "goodscount");
            return (Criteria) this;
        }

        public Criteria andGoodscountNotBetween(String value1, String value2) {
            addCriterion("goodscount not between", value1, value2, "goodscount");
            return (Criteria) this;
        }

        public Criteria andAllgoodscountIsNull() {
            addCriterion("allgoodscount is null");
            return (Criteria) this;
        }

        public Criteria andAllgoodscountIsNotNull() {
            addCriterion("allgoodscount is not null");
            return (Criteria) this;
        }

        public Criteria andAllgoodscountEqualTo(String value) {
            addCriterion("allgoodscount =", value, "allgoodscount");
            return (Criteria) this;
        }

        public Criteria andAllgoodscountNotEqualTo(String value) {
            addCriterion("allgoodscount <>", value, "allgoodscount");
            return (Criteria) this;
        }

        public Criteria andAllgoodscountGreaterThan(String value) {
            addCriterion("allgoodscount >", value, "allgoodscount");
            return (Criteria) this;
        }

        public Criteria andAllgoodscountGreaterThanOrEqualTo(String value) {
            addCriterion("allgoodscount >=", value, "allgoodscount");
            return (Criteria) this;
        }

        public Criteria andAllgoodscountLessThan(String value) {
            addCriterion("allgoodscount <", value, "allgoodscount");
            return (Criteria) this;
        }

        public Criteria andAllgoodscountLessThanOrEqualTo(String value) {
            addCriterion("allgoodscount <=", value, "allgoodscount");
            return (Criteria) this;
        }

        public Criteria andAllgoodscountLike(String value) {
            addCriterion("allgoodscount like", value, "allgoodscount");
            return (Criteria) this;
        }

        public Criteria andAllgoodscountNotLike(String value) {
            addCriterion("allgoodscount not like", value, "allgoodscount");
            return (Criteria) this;
        }

        public Criteria andAllgoodscountIn(List<String> values) {
            addCriterion("allgoodscount in", values, "allgoodscount");
            return (Criteria) this;
        }

        public Criteria andAllgoodscountNotIn(List<String> values) {
            addCriterion("allgoodscount not in", values, "allgoodscount");
            return (Criteria) this;
        }

        public Criteria andAllgoodscountBetween(String value1, String value2) {
            addCriterion("allgoodscount between", value1, value2, "allgoodscount");
            return (Criteria) this;
        }

        public Criteria andAllgoodscountNotBetween(String value1, String value2) {
            addCriterion("allgoodscount not between", value1, value2, "allgoodscount");
            return (Criteria) this;
        }

        public Criteria andYeargoodscountIsNull() {
            addCriterion("yeargoodscount is null");
            return (Criteria) this;
        }

        public Criteria andYeargoodscountIsNotNull() {
            addCriterion("yeargoodscount is not null");
            return (Criteria) this;
        }

        public Criteria andYeargoodscountEqualTo(String value) {
            addCriterion("yeargoodscount =", value, "yeargoodscount");
            return (Criteria) this;
        }

        public Criteria andYeargoodscountNotEqualTo(String value) {
            addCriterion("yeargoodscount <>", value, "yeargoodscount");
            return (Criteria) this;
        }

        public Criteria andYeargoodscountGreaterThan(String value) {
            addCriterion("yeargoodscount >", value, "yeargoodscount");
            return (Criteria) this;
        }

        public Criteria andYeargoodscountGreaterThanOrEqualTo(String value) {
            addCriterion("yeargoodscount >=", value, "yeargoodscount");
            return (Criteria) this;
        }

        public Criteria andYeargoodscountLessThan(String value) {
            addCriterion("yeargoodscount <", value, "yeargoodscount");
            return (Criteria) this;
        }

        public Criteria andYeargoodscountLessThanOrEqualTo(String value) {
            addCriterion("yeargoodscount <=", value, "yeargoodscount");
            return (Criteria) this;
        }

        public Criteria andYeargoodscountLike(String value) {
            addCriterion("yeargoodscount like", value, "yeargoodscount");
            return (Criteria) this;
        }

        public Criteria andYeargoodscountNotLike(String value) {
            addCriterion("yeargoodscount not like", value, "yeargoodscount");
            return (Criteria) this;
        }

        public Criteria andYeargoodscountIn(List<String> values) {
            addCriterion("yeargoodscount in", values, "yeargoodscount");
            return (Criteria) this;
        }

        public Criteria andYeargoodscountNotIn(List<String> values) {
            addCriterion("yeargoodscount not in", values, "yeargoodscount");
            return (Criteria) this;
        }

        public Criteria andYeargoodscountBetween(String value1, String value2) {
            addCriterion("yeargoodscount between", value1, value2, "yeargoodscount");
            return (Criteria) this;
        }

        public Criteria andYeargoodscountNotBetween(String value1, String value2) {
            addCriterion("yeargoodscount not between", value1, value2, "yeargoodscount");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNull() {
            addCriterion("updateuser is null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNotNull() {
            addCriterion("updateuser is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserEqualTo(String value) {
            addCriterion("updateuser =", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotEqualTo(String value) {
            addCriterion("updateuser <>", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThan(String value) {
            addCriterion("updateuser >", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThanOrEqualTo(String value) {
            addCriterion("updateuser >=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThan(String value) {
            addCriterion("updateuser <", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThanOrEqualTo(String value) {
            addCriterion("updateuser <=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLike(String value) {
            addCriterion("updateuser like", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotLike(String value) {
            addCriterion("updateuser not like", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIn(List<String> values) {
            addCriterion("updateuser in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotIn(List<String> values) {
            addCriterion("updateuser not in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserBetween(String value1, String value2) {
            addCriterion("updateuser between", value1, value2, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotBetween(String value1, String value2) {
            addCriterion("updateuser not between", value1, value2, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}