package com.crm.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table stock_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class StockInfo {
    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.goodsID
     *
     * @mbg.generated
     */
    private String goodsid;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.goodsname
     *
     * @mbg.generated
     */
    private String goodsname;

    /**
     * Database Column Remarks:
     *   商品类别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.goodsype
     *
     * @mbg.generated
     */
    private String goodsype;

    /**
     * Database Column Remarks:
     *   商品当前存量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.goodscount
     *
     * @mbg.generated
     */
    private String goodscount;

    /**
     * Database Column Remarks:
     *   历史商品总量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.allgoodscount
     *
     * @mbg.generated
     */
    private String allgoodscount;

    /**
     * Database Column Remarks:
     *   当年商品总量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.yeargoodscount
     *
     * @mbg.generated
     */
    private String yeargoodscount;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.updateuser
     *
     * @mbg.generated
     */
    private String updateuser;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.goodsID
     *
     * @return the value of stock_info.goodsID
     *
     * @mbg.generated
     */
    public String getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.goodsID
     *
     * @param goodsid the value for stock_info.goodsID
     *
     * @mbg.generated
     */
    public void setGoodsid(String goodsid) {
        this.goodsid = goodsid == null ? null : goodsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.goodsname
     *
     * @return the value of stock_info.goodsname
     *
     * @mbg.generated
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.goodsname
     *
     * @param goodsname the value for stock_info.goodsname
     *
     * @mbg.generated
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.goodsype
     *
     * @return the value of stock_info.goodsype
     *
     * @mbg.generated
     */
    public String getGoodsype() {
        return goodsype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.goodsype
     *
     * @param goodsype the value for stock_info.goodsype
     *
     * @mbg.generated
     */
    public void setGoodsype(String goodsype) {
        this.goodsype = goodsype == null ? null : goodsype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.goodscount
     *
     * @return the value of stock_info.goodscount
     *
     * @mbg.generated
     */
    public String getGoodscount() {
        return goodscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.goodscount
     *
     * @param goodscount the value for stock_info.goodscount
     *
     * @mbg.generated
     */
    public void setGoodscount(String goodscount) {
        this.goodscount = goodscount == null ? null : goodscount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.allgoodscount
     *
     * @return the value of stock_info.allgoodscount
     *
     * @mbg.generated
     */
    public String getAllgoodscount() {
        return allgoodscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.allgoodscount
     *
     * @param allgoodscount the value for stock_info.allgoodscount
     *
     * @mbg.generated
     */
    public void setAllgoodscount(String allgoodscount) {
        this.allgoodscount = allgoodscount == null ? null : allgoodscount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.yeargoodscount
     *
     * @return the value of stock_info.yeargoodscount
     *
     * @mbg.generated
     */
    public String getYeargoodscount() {
        return yeargoodscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.yeargoodscount
     *
     * @param yeargoodscount the value for stock_info.yeargoodscount
     *
     * @mbg.generated
     */
    public void setYeargoodscount(String yeargoodscount) {
        this.yeargoodscount = yeargoodscount == null ? null : yeargoodscount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.remark
     *
     * @return the value of stock_info.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.remark
     *
     * @param remark the value for stock_info.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.updateuser
     *
     * @return the value of stock_info.updateuser
     *
     * @mbg.generated
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.updateuser
     *
     * @param updateuser the value for stock_info.updateuser
     *
     * @mbg.generated
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.update_time
     *
     * @return the value of stock_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.update_time
     *
     * @param updateTime the value for stock_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}