package com.crm.entity;

import com.baomidou.mybatisplus.annotation.TableId;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserInfo {
    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USERID
     *
     * @mbg.generated
     */
    @TableId
    private String userid;

    /**
     * Database Column Remarks:
     *   登录id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.LOGINID
     *
     * @mbg.generated
     */
    private String loginid;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USERNAME
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   属性1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ATTRIBUTE1
     *
     * @mbg.generated
     */
    private String attribute1;

    /**
     * Database Column Remarks:
     *   属性2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ATTRIBUTE2
     *
     * @mbg.generated
     */
    private String attribute2;

    /**
     * Database Column Remarks:
     *   属性3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ATTRIBUTE3
     *
     * @mbg.generated
     */
    private String attribute3;

    /**
     * Database Column Remarks:
     *   属性4
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ATTRIBUTE4
     *
     * @mbg.generated
     */
    private String attribute4;

    /**
     * Database Column Remarks:
     *   属性5
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ATTRIBUTE5
     *
     * @mbg.generated
     */
    private String attribute5;

    /**
     * Database Column Remarks:
     *   属性6
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ATTRIBUTE6
     *
     * @mbg.generated
     */
    private String attribute6;

    /**
     * Database Column Remarks:
     *   属性7
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ATTRIBUTE7
     *
     * @mbg.generated
     */
    private String attribute7;

    /**
     * Database Column Remarks:
     *   状态 0正常 1锁定
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.MOBILETEL
     *
     * @mbg.generated
     */
    private String mobiletel;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USERID
     *
     * @return the value of user_info.USERID
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USERID
     *
     * @param userid the value for user_info.USERID
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.LOGINID
     *
     * @return the value of user_info.LOGINID
     *
     * @mbg.generated
     */
    public String getLoginid() {
        return loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.LOGINID
     *
     * @param loginid the value for user_info.LOGINID
     *
     * @mbg.generated
     */
    public void setLoginid(String loginid) {
        this.loginid = loginid == null ? null : loginid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USERNAME
     *
     * @return the value of user_info.USERNAME
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USERNAME
     *
     * @param username the value for user_info.USERNAME
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.PASSWORD
     *
     * @return the value of user_info.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.PASSWORD
     *
     * @param password the value for user_info.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ATTRIBUTE1
     *
     * @return the value of user_info.ATTRIBUTE1
     *
     * @mbg.generated
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ATTRIBUTE1
     *
     * @param attribute1 the value for user_info.ATTRIBUTE1
     *
     * @mbg.generated
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1 == null ? null : attribute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ATTRIBUTE2
     *
     * @return the value of user_info.ATTRIBUTE2
     *
     * @mbg.generated
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ATTRIBUTE2
     *
     * @param attribute2 the value for user_info.ATTRIBUTE2
     *
     * @mbg.generated
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2 == null ? null : attribute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ATTRIBUTE3
     *
     * @return the value of user_info.ATTRIBUTE3
     *
     * @mbg.generated
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ATTRIBUTE3
     *
     * @param attribute3 the value for user_info.ATTRIBUTE3
     *
     * @mbg.generated
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3 == null ? null : attribute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ATTRIBUTE4
     *
     * @return the value of user_info.ATTRIBUTE4
     *
     * @mbg.generated
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ATTRIBUTE4
     *
     * @param attribute4 the value for user_info.ATTRIBUTE4
     *
     * @mbg.generated
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4 == null ? null : attribute4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ATTRIBUTE5
     *
     * @return the value of user_info.ATTRIBUTE5
     *
     * @mbg.generated
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ATTRIBUTE5
     *
     * @param attribute5 the value for user_info.ATTRIBUTE5
     *
     * @mbg.generated
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5 == null ? null : attribute5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ATTRIBUTE6
     *
     * @return the value of user_info.ATTRIBUTE6
     *
     * @mbg.generated
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ATTRIBUTE6
     *
     * @param attribute6 the value for user_info.ATTRIBUTE6
     *
     * @mbg.generated
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6 == null ? null : attribute6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ATTRIBUTE7
     *
     * @return the value of user_info.ATTRIBUTE7
     *
     * @mbg.generated
     */
    public String getAttribute7() {
        return attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ATTRIBUTE7
     *
     * @param attribute7 the value for user_info.ATTRIBUTE7
     *
     * @mbg.generated
     */
    public void setAttribute7(String attribute7) {
        this.attribute7 = attribute7 == null ? null : attribute7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.STATUS
     *
     * @return the value of user_info.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.STATUS
     *
     * @param status the value for user_info.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.MOBILETEL
     *
     * @return the value of user_info.MOBILETEL
     *
     * @mbg.generated
     */
    public String getMobiletel() {
        return mobiletel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.MOBILETEL
     *
     * @param mobiletel the value for user_info.MOBILETEL
     *
     * @mbg.generated
     */
    public void setMobiletel(String mobiletel) {
        this.mobiletel = mobiletel == null ? null : mobiletel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.EMAIL
     *
     * @return the value of user_info.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.EMAIL
     *
     * @param email the value for user_info.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_time
     *
     * @return the value of user_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_time
     *
     * @param updateTime the value for user_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}