package com.crm.dao;

import com.crm.entity.CommoditiesInfo;
import com.crm.entity.CommoditiesInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommoditiesInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodities_info
     *
     * @mbg.generated
     */
    long countByExample(CommoditiesInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodities_info
     *
     * @mbg.generated
     */
    int deleteByExample(CommoditiesInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodities_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String goodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodities_info
     *
     * @mbg.generated
     */
    int insert(CommoditiesInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodities_info
     *
     * @mbg.generated
     */
    int insertSelective(CommoditiesInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodities_info
     *
     * @mbg.generated
     */
    List<CommoditiesInfo> selectByExample(CommoditiesInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodities_info
     *
     * @mbg.generated
     */
    CommoditiesInfo selectByPrimaryKey(String goodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodities_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CommoditiesInfo record, @Param("example") CommoditiesInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodities_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CommoditiesInfo record, @Param("example") CommoditiesInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodities_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CommoditiesInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodities_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CommoditiesInfo record);
}